### ISSUE TITLE
Add index content for chest and triceps

### ISSUE THREAD

**Issue by TylerGauntlett** [TylerGauntlett/gym_sesh#12]
Requires https://github.com/TylerGauntlett/gym_sesh/issues/11 to be completed first

Chest/Triceps button should appear similarly to the Back/Biceps button after the issue above has been completed.

Code should be added here https://github.com/TylerGauntlett/gym_sesh/blob/master/index.html#L159

Update notes.md with content added to table

**Comment by stnbnvdz** [comment]
Can I work on this?

**Comment by TylerGauntlett** [comment]
Sure @stnbnvdz. I modified the data structure to support multiple types. Follow the `back_biceps` data structure and add code here https://github.com/TylerGauntlett/gym_sesh/blob/master/index.html#L159

**Comment by TylerGauntlett** [comment]
Resolved with https://github.com/TylerGauntlett/gym_sesh/pull/25
