### ISSUE TITLE
Add index content for legs and shoulders

### ISSUE THREAD

**Issue by TylerGauntlett** [TylerGauntlett/gym_sesh#13]
Requires https://github.com/TylerGauntlett/gym_sesh/issues/11 to be completed first

Legs/Shoulders button should appear similarly to the Back/Biceps button after the issue above has been completed.

Code should be added here https://github.com/TylerGauntlett/gym_sesh/blob/master/index.html#L160

Update notes.md with content added to table

**Comment by stnbnvdz** [comment]
Will also work on this.

**Comment by TylerGauntlett** [comment]
Resolved with https://github.com/TylerGauntlett/gym_sesh/pull/25
