### ISSUE TITLE
Add chest and triceps details to exercise page

### ISSUE THREAD

**Issue by TylerGauntlett** [TylerGauntlett/gym_sesh#14]
Requires https://github.com/TylerGauntlett/gym_sesh/issues/12 to be completed first

Add content for 6 chest and triceps workouts similar to the back and bicep details page

Code should be added here https://github.com/TylerGauntlett/gym_sesh/blob/master/exercises.html#L267

Update notes.md with exercises

**Comment by boxabhi** [comment]
@TylerGauntlett I would like to work on it.

**Comment by TylerGauntlett** [comment]
@boxabhi, feel free to make a PR to master and submit the link here. Might be easier with #12 finished first but it’s up to you on what you wish to tackle

**Comment by TylerGauntlett** [comment]
@boxabhi i modified the data structure to support multiple types. see link above

**Comment by TylerGauntlett** [comment]
Resolved with https://github.com/TylerGauntlett/gym_sesh/pull/25
